import type {
  AiModelOption,
  ChoiceOption,
  GrowthPresetOption,
  ModelAlternative,
  PlannerComparisonResult,
  PlannerFormState,
  PlannerStepMeta,
  PlannerWizardContent,
  SearchTierOption,
  TokenPresetOption,
} from "@/features/planner/types/planner";

const LOREM =
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.";

const CANNED_NOTE =
  "Responses below are canned, not generated by a model. Team is still deciding the orchestration approach - see the note on this screens tasks. Responses below are cks. Responses below are canned, not generated by a model. Responses below are canned, not generated by a model. Team is still deciding the orchestration approach - see the note on this screens tasks. Responses below are cks. Responses below are canned, not generated by a model.";

export const PLANNER_STEPS: PlannerStepMeta[] = [
  {
    step: 1,
    eyebrow: "AI Model",
    title: "Which AI Model would you like to start with?",
    description: CANNED_NOTE,
  },
  {
    step: 2,
    eyebrow: "Business Knowledge",
    title: "Should the AI answer using your business documents?",
    description: CANNED_NOTE,
  },
  {
    step: 3,
    eyebrow: "Expected Usage",
    title: "How much will the solution be used?",
    description: CANNED_NOTE,
  },
  {
    step: 4,
    eyebrow: "Token Sizes",
    title: "How much text will each AI interactions use?",
    description: CANNED_NOTE,
  },
  {
    step: 5,
    eyebrow: "Hosting and Growth",
    title: "What supporting costs should the estimate include?",
    description: CANNED_NOTE,
  },
  {
    step: 6,
    eyebrow: "Review",
    title: "Review your assumptions",
    description: CANNED_NOTE,
  },
];

export const AI_MODELS: AiModelOption[] = [
  {
    id: "gpt-4o",
    name: "GPT-4o",
    description: LOREM,
    inputPrice: "$0.0025",
    outputPrice: "$0.0100",
  },
  {
    id: "gpt-4o-mini",
    name: "GPT-4o mini",
    description: LOREM,
    inputPrice: "$0.0005",
    outputPrice: "$0.0165",
  },
  {
    id: "gpt-4-1",
    name: "GPT-4.1",
    description: LOREM,
    inputPrice: "$0.0030",
    outputPrice: "$0.0120",
  },
  {
    id: "gpt-4-1-mini",
    name: "GPT-4.1 mini",
    description: LOREM,
    inputPrice: "$0.0008",
    outputPrice: "$0.0140",
  },
  {
    id: "gpt-4-turbo",
    name: "GPT-4 Turbo",
    description: LOREM,
    inputPrice: "$0.0015",
    outputPrice: "$0.0090",
  },
  {
    id: "gpt-3-5-turbo",
    name: "GPT-3.5 Turbo",
    description: LOREM,
    inputPrice: "$0.0004",
    outputPrice: "$0.0012",
  },
];

export const BUSINESS_DOCUMENT_CHOICES: ChoiceOption[] = [
  {
    id: "yes",
    title: "Yes – Search my documents",
    description: LOREM,
  },
  {
    id: "no",
    title: "No – use the AI model only",
    description: LOREM,
  },
];

export const SEARCH_TIERS: SearchTierOption[] = [
  {
    id: "basic",
    title: "Basic – up to 10 GB",
    description: LOREM,
    monthlyCost: "$19.50",
  },
  {
    id: "standard",
    title: "Standard – up to 100 GB",
    description: LOREM,
    monthlyCost: "$29.70",
  },
  {
    id: "premium",
    title: "Premium – up to 1 TB",
    description: LOREM,
    monthlyCost: "$49.90",
  },
];

export const SUPPORTING_COST_CHOICES: ChoiceOption[] = [
  {
    id: "yes",
    title: "Yes – Search my documents",
    description: LOREM,
  },
  {
    id: "no",
    title: "No – use the AI model only",
    description: LOREM,
  },
];

export const INPUT_TOKEN_PRESETS: TokenPresetOption[] = [
  { id: "short", label: "Short", value: 400 },
  { id: "standard", label: "Standard", value: 800 },
  { id: "long", label: "Long", value: 2000 },
];

export const OUTPUT_TOKEN_PRESETS: TokenPresetOption[] = [
  { id: "short", label: "Short", value: 190 },
  { id: "standard", label: "Standard", value: 400 },
  { id: "long", label: "Long", value: 1000 },
];

export const GROWTH_PRESETS: GrowthPresetOption[] = [
  { id: "short", label: "Short", value: 400 },
  { id: "standard", label: "Standard", value: 800 },
  { id: "long", label: "Long", value: 2000 },
];

export const DEFAULT_PLANNER_FORM: PlannerFormState = {
  modelId: "gpt-4o-mini",
  useBusinessDocuments: false,
  searchTierId: "standard",
  activePeople: 500,
  interactionsPerDay: 5,
  inputTokenPreset: "standard",
  customInputTokens: 800,
  outputTokenPreset: "standard",
  customOutputTokens: 400,
  includeSupportingCosts: true,
  monthlyGrowthPreset: "standard",
  customGrowthValue: 800,
};

export const PLANNER_WIZARD_CONTENT: PlannerWizardContent = {
  steps: PLANNER_STEPS,
  models: AI_MODELS,
  businessDocumentChoices: BUSINESS_DOCUMENT_CHOICES,
  searchTiers: SEARCH_TIERS,
  supportingCostChoices: SUPPORTING_COST_CHOICES,
  inputTokenPresets: INPUT_TOKEN_PRESETS,
  outputTokenPresets: OUTPUT_TOKEN_PRESETS,
  growthPresets: GROWTH_PRESETS,
  defaultForm: DEFAULT_PLANNER_FORM,
};

export const PLANNER_ESTIMATE_BANNER =
  "Live Browser Estimate: These figures are mock data, not actual Azure Cost Management Data. Real numbers appear once Cost API is connected.";

export const MODEL_ALTERNATIVES: ModelAlternative[] = [
  {
    id: "gpt-4o-mini",
    name: "Gpt- 4o mini",
    description: "This is the model you selected.",
    tier: "selected",
    monthlyCost: "$29.70",
    difference: "Baseline",
    vsSelected: "Baseline",
    annualCost: "$635.11",
    costPerPerson: "$635.11",
    costPerInteraction: "$635.11",
  },
  {
    id: "gpt-4-1-nano",
    name: "Gpt- 4.1 nano",
    description: "A lower cost model for the exact same usage",
    tier: "lower",
    monthlyCost: "$29.70",
    difference: "Save $635.11",
    vsSelected: "Baseline",
    annualCost: "$635.11",
    costPerPerson: "$635.11",
    costPerInteraction: "$635.11",
    isCheaper: true,
  },
  {
    id: "gpt-4-1-mini",
    name: "Gpt- 4.1 mini",
    description: "A higher cost model for the exact same usage",
    tier: "higher",
    monthlyCost: "$29.70",
    difference: "Save $635.11",
    vsSelected: "167% more",
    annualCost: "$635.11",
    costPerPerson: "$635.11",
    costPerInteraction: "$635.11",
  },
];

export function buildPlannerComparison(form: PlannerFormState): PlannerComparisonResult {
  const selected =
    MODEL_ALTERNATIVES.find((item) => item.id === form.modelId) ?? MODEL_ALTERNATIVES[0]!;

  const comparisonRows: ModelAlternative[] = [
    {
      ...selected,
      tier: "selected",
      name: "GPT- 4o mini",
      description: "Selected model - selected",
      monthlyCost: "$29.70",
      difference: "Baseline",
      vsSelected: "Baseline",
      annualCost: "$635.11",
      costPerPerson: "$0.059",
      costPerInteraction: "$0.0004",
    },
    {
      id: "gpt-4-1-nano",
      name: "GPT- 4.1 nano",
      description: "Lower cost option - cheaper",
      tier: "lower",
      monthlyCost: "$29.70",
      difference: "Save $635.11",
      vsSelected: "Baseline",
      annualCost: "$635.11",
      costPerPerson: "$0.059",
      costPerInteraction: "$0.0004",
      isCheaper: true,
    },
    {
      id: "gpt-4-1-mini",
      name: "GPT- 4.1 nano",
      description: "Lower cost option - cheaper",
      tier: "higher",
      monthlyCost: "$29.70",
      difference: "Save $635.11",
      vsSelected: "167% more",
      annualCost: "$635.11",
      costPerPerson: "$0.059",
      costPerInteraction: "$0.0004",
    },
  ];

  return {
    alternatives: MODEL_ALTERNATIVES,
    comparisonRows,
  };
}
