export const SCENARIOS = [
  {
    id: "A",
    label: "Option A",
    model: "GPT-4o",
    name: "GPT-4o",
    description: "A balanced general-purpose model without document search.",
    forceRag: false,
  },
  {
    id: "B",
    label: "Option B",
    model: "GPT-4.1",
    name: "GPT-4.1",
    description: "A strong model for instruction following and complex tasks.",
    forceRag: false,
  },
  {
    id: "C",
    label: "Option C",
    model: "GPT-4o",
    name: "GPT-4o + your content",
    description: "GPT-4o with Azure AI Search to answer from your documents.",
    forceRag: true,
  },
];

export function getScenarios(selectedModel = "GPT-4o") {
  return SCENARIOS.map((scenario) =>
    scenario.id === "A"
      ? {
          ...scenario,
          model: selectedModel,
          name: selectedModel,
          description: `Your selected ${selectedModel} model without document search.`,
        }
      : scenario,
  );
}

export const RESOURCE_OPTIONS = [
  {
    key: "openai",
    label: "AI model usage",
    technicalName: "Azure OpenAI",
    description:
      "The text sent to and generated by your AI model. This is usually the main usage-based cost in an AI application.",
  },
  {
    key: "rag",
    label: "Use your own content",
    technicalName: "RAG + Azure AI Search",
    description:
      "Lets the AI search your organization’s documents before answering. Include this when answers should use trusted company content.",
  },
  {
    key: "storage",
    label: "Files and app data",
    technicalName: "Storage + Azure SQL",
    description:
      "Stores source documents, the searchable knowledge base, and structured application data.",
  },
  {
    key: "compute",
    label: "App hosting",
    technicalName: "App Service + Functions",
    description:
      "Runs the website, API, and background jobs around the AI model. The AI model itself is priced separately.",
  },
  {
    key: "apim",
    label: "Secure API access",
    technicalName: "API Management",
    description:
      "Adds a managed gateway for authentication, rate limits, policies, and controlled access to your APIs.",
  },
  {
    key: "monitoring",
    label: "Usage and error tracking",
    technicalName: "Azure Monitor",
    description:
      "Collects logs and diagnostic information so your team can understand usage and troubleshoot problems.",
  },
  {
    key: "identity",
    label: "User sign-in",
    technicalName: "Microsoft Entra ID",
    description:
      "Provides secure sign-in and access control for employees, customers, or partners using the solution.",
  },
  {
    key: "finetuning",
    label: "Custom model training",
    technicalName: "Fine-tuning",
    description:
      "Trains a model on examples for specialized behavior. Most first versions do not need this; prompt design and document search are often enough.",
  },
];

export const SECTION_COPY = {
  openai: {
    title: "AI model usage",
    description: "Tell us how many people will use the AI and how much text it will process.",
  },
  rag: {
    title: "Use your own content",
    description: "Estimate the cost of preparing and searching your organization’s documents.",
  },
  storage: {
    title: "Files and app data",
    description: "Include the space needed for documents, search data, and the application database.",
  },
  compute: {
    title: "App hosting",
    description: "Choose how the web app, API, and background work will be hosted.",
  },
  apim: {
    title: "Secure API access",
    description: "Choose a managed gateway plan if APIs need centralized protection and control.",
  },
  monitoring: {
    title: "Usage and error tracking",
    description: "Estimate how much diagnostic data the solution will collect and retain.",
  },
  identity: {
    title: "User sign-in",
    description: "Include paid identity features only when the solution needs them.",
  },
  finetuning: {
    title: "Custom model training",
    description: "Include one-time training and optional always-ready hosting costs.",
  },
  global: {
    title: "Planning buffer",
    description: "Add realistic allowances for retries, growth, and other fixed Azure services.",
  },
};

export const SELECT_OPTIONS = {
  models: [
    { value: "GPT-4o", label: "GPT-4o — balanced performance" },
    { value: "GPT-4o mini", label: "GPT-4o mini — lower cost" },
    { value: "GPT-4.1", label: "GPT-4.1 — complex tasks" },
    { value: "GPT-4 Turbo", label: "GPT-4 Turbo — legacy workloads" },
    { value: "o1", label: "o1 — advanced reasoning" },
    { value: "o3", label: "o3 — advanced reasoning" },
    { value: "o4-mini", label: "o4-mini — efficient reasoning" },
    { value: "GPT-3.5-Turbo", label: "GPT-3.5 Turbo — legacy, low cost" },
  ],
  billingModes: [
    { value: "payg", label: "Pay only for what you use" },
    { value: "ptu", label: "Reserve dedicated capacity" },
    { value: "batch", label: "Process flexible work later" },
  ],
  regionTypes: [
    { value: "global", label: "Best global availability" },
    { value: "datazone", label: "Keep data within a geography" },
    { value: "regional", label: "Keep processing in one region" },
  ],
  ptuCommitments: [
    { value: "hourly", label: "Hourly, no commitment" },
    { value: "monthly", label: "One month" },
    { value: "annual", label: "One year" },
  ],
  ptuScopes: [
    { value: "global", label: "Global" },
    { value: "regional", label: "Single Azure region" },
  ],
  embeddingModels: [
    { value: "small", label: "Standard search indexing" },
    { value: "large", label: "Higher-quality search indexing" },
  ],
  reindexFrequencies: [
    { value: "onetime", label: "Set up once" },
    { value: "recurring", label: "Refresh every month" },
  ],
  searchTiers: [
    { value: "free", label: "Free — prototype only" },
    { value: "basic", label: "Basic — small production app" },
    { value: "standard", label: "Standard — more scale" },
  ],
  sqlTiers: [
    { value: "basic", label: "Basic — light use" },
    { value: "standard", label: "Standard — typical app" },
    { value: "premium", label: "Premium — demanding app" },
  ],
  appServiceTiers: [
    { value: "none", label: "No web app hosting" },
    { value: "basic", label: "Basic — one small app" },
    { value: "standard", label: "Standard — production app" },
  ],
  functionsPlans: [
    { value: "consumption", label: "Pay per background task" },
    { value: "premium", label: "Keep background workers ready" },
  ],
  apimTiers: [
    { value: "developer", label: "Developer — testing only" },
    { value: "basic", label: "Basic — light production use" },
    { value: "standard", label: "Standard — production use" },
    { value: "premium", label: "Premium — enterprise scale" },
  ],
  entraTiers: [
    { value: "free", label: "Free sign-in features" },
    { value: "p1", label: "Plan 1 — advanced access" },
    { value: "p2", label: "Plan 2 — risk protection" },
  ],
  keyVaultOptions: [
    { value: "included", label: "Include secure secrets storage" },
    { value: "excluded", label: "Do not include it" },
  ],
  hostingOptions: [
    { value: "off", label: "Only pay when training" },
    { value: "on", label: "Keep the custom model ready" },
  ],
};

export function createInitialFormValues() {
  return {
    resources: {
      openai: true,
      rag: true,
      storage: false,
      compute: false,
      apim: false,
      monitoring: false,
      identity: false,
      finetuning: false,
    },
    openai: {
      model: "GPT-4o",
      billingMode: "payg",
      regionType: "global",
      users: 500,
      requestsPerDay: 5,
      avgPromptTokens: 800,
      avgCompletionTokens: 400,
      historyTurns: 1,
      systemOverheadTokens: 300,
      maxTokensCap: 0,
      ptuCount: 15,
      ptuCommitment: "annual",
      ptuScope: "global",
      batchPct: 30,
    },
    rag: {
      embeddingModel: "small",
      numDocuments: 2000,
      avgDocTokens: 600,
      chunkSize: 300,
      reindexFreq: "onetime",
      vectorQueriesPerDay: 200,
      searchTier: "basic",
      replicaCount: 1,
    },
    storage: {
      docStorageGB: 5,
      storageGrowthPct: 5,
      vectorStorageGB: 2,
      sqlTier: "standard",
    },
    compute: {
      appServiceTier: "basic",
      functionsPlan: "consumption",
      environments: { dev: true, test: false, prod: true },
    },
    apim: { apimTier: "developer" },
    monitoring: { logGB: 10, retentionDays: 30 },
    identity: { entraTier: "free", licensedUsers: 500, keyVaultIncluded: true },
    finetuning: { hostingOn: false, trainingCost: 0 },
    global: {
      retryOverheadPct: 10,
      growthPct: 10,
      infraOverheadUsd: 40,
    },
  };
}
